name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with: 
          python-version: 3.5
      - name: Run make
        run: make install
      - name: Run make
        run: make lint
      - name: Test
        run: test
    
